-- Import personel dari foto (NIK, nama, jabatan).
-- Kolom id di foto = nik (Nomor Id Karyawan).
-- idpersonel diisi otomatis.
--
-- Catatan:
-- 1. NIK 96477 di foto dipakai Agus Hariyanto dan Idris. Idris sementara NIK 96477B.
-- 2. NIK 86077 di foto dipakai Eko Siantoro dan Nanang Iriyanto. Nanang sementara NIK 86077B.
-- 3. Ferry Irawan dan Sutarno (B) di foto tidak ada NIK. Sementara NOID-...
-- Ubah NIK sementara itu setelah dicek ulang.

INSERT INTO personel (nik, namapersonel, jabatan, created_at, updated_at) VALUES
('86817', 'A. Rohman S. W.', 'Rigger / Mechanic', NOW(), NOW()),
('96624', 'Aang Nartono', 'Lead Rigger / Scaffolding Assessor', NOW(), NOW()),
('20635', 'Abdul Jamal', 'Lead Rigger / Scaffolding Assessor', NOW(), NOW()),
('117764', 'Abdurohim', 'Rigger / Scaffolder', NOW(), NOW()),
('118490', 'Achmad Rifa''i', 'Rigger / Scaffolder', NOW(), NOW()),
('76472', 'Ade Patdy Lambe', 'Lead Rigger / Scaffolder Technician', NOW(), NOW()),
('6386', 'Ade Roby H.', 'Lead Rigger / Scaffolding Assessor', NOW(), NOW()),
('117579', 'Adi Alis Sandi', 'Rigger / Scaffolder', NOW(), NOW()),
('96477', 'Agus Hariyanto', 'Lead Rigger / Scaffolder Technician', NOW(), NOW()),
('124593', 'Agus Hernanto', 'HTW/HWC Technician', NOW(), NOW()),
('118414', 'Ahmad Nabil Seriv', 'Rigger / Scaffolder', NOW(), NOW()),
('40581', 'Ahmad Sugih Hermawan', 'Lead Rigger / Scaffolding Assessor', NOW(), NOW()),
('117580', 'Ahmad Syafi''i', 'Rigger / Scaffolder', NOW(), NOW()),
('123398', 'Ahmad Triyoga', 'Welder', NOW(), NOW()),
('718', 'Aip Hidayat', 'Mech. / Piping Supv.', NOW(), NOW()),
('6232', 'Ali Kurniawan', 'Lead Rigger / Scaffolding Assessor', NOW(), NOW()),
('91330', 'Ananto Supriyo N', 'Field Surveyor', NOW(), NOW()),
('1121', 'Arum Rachmanto', 'Mech. / Piping Supv.', NOW(), NOW()),
('1078', 'Asep Hendra', 'Mech./Piping Supv. / Surveyor', NOW(), NOW()),
('118045', 'Asri Maradona', 'Welder', NOW(), NOW()),
('120197', 'Azhar Permadi', 'HTW/HWC Technician', NOW(), NOW()),
('77245', 'Bahrudin', 'Mech. / Piping Supv.', NOW(), NOW()),
('75651', 'Bakhrudin', 'Lead Rigger / Scaffolding Assessor', NOW(), NOW()),
('117435', 'Baladi bin Mupidi', 'Rigger / Scaffolder', NOW(), NOW()),
('1139', 'Broni', 'Mech. / Piping Supv.', NOW(), NOW()),
('117518', 'Cahyana', 'Rigger / Scaffolder', NOW(), NOW()),
('91813', 'Casyanto', 'Lead Rigger / Scaffolding Assessor', NOW(), NOW()),
('101989', 'Danuh', 'Rigger / Scaffolder', NOW(), NOW()),
('1074', 'David Lujihale', 'Mech. / Piping Supv.', NOW(), NOW()),
('77436', 'Dedi Kurniawan', 'Lead Rigger / Scaffolding Assessor', NOW(), NOW()),
('117652', 'Dias Abadi F.', 'Rigger / Scaffolder', NOW(), NOW()),
('77228', 'Didik Suharsono', 'Rigger / Scaffolder', NOW(), NOW()),
('117647', 'Dodi Iswanto', 'Rigger / Scaffolding Assessor', NOW(), NOW()),
('118443', 'Dodi Setiadi', 'Rigger / Scaffolder', NOW(), NOW()),
('118603', 'Dodik Prasetyo Hermanto', 'Rigger / Scaffolder', NOW(), NOW()),
('77768', 'Doni Pradono', 'Mech. / Piping Supv.', NOW(), NOW()),
('96362', 'Durinto', 'Mech. / Piping Supv.', NOW(), NOW()),
('22061', 'Durmadi', 'Lead Rigger / Scaffolding Assessor', NOW(), NOW()),
('6384', 'Dusye Rehardus Lainsamputty', 'Lead Rigger / Scaffolder Technician', NOW(), NOW()),
('117801', 'Dwi Sasongko', 'Rigger / Scaffolder', NOW(), NOW()),
('97992', 'Edi Susanto', 'Lead Rigger / Scaffolder Technician', NOW(), NOW()),
('97828', 'Erick Arbianto', 'Field Surveyor', NOW(), NOW()),
('117954', 'Fahrudin', 'Welder', NOW(), NOW()),
('117646', 'Faisal Rachman', 'Rigger / Scaffolder', NOW(), NOW()),
('NOID-FERRY-IRAWAN', 'Ferry Irawan', 'Site Surveyor', NOW(), NOW()),
('1055', 'Fery Liston', 'Mech. / Piping Supv.', NOW(), NOW()),
('123822', 'H. Sanwani', 'HTW/HWC Technician', NOW(), NOW()),
('44982', 'Habib Setiawan', 'Lead Rigger / Scaffolding Assessor', NOW(), NOW()),
('117436', 'Hadi Bangbang S.', 'Rigger / Mechanic', NOW(), NOW()),
('719', 'Hari Suswanto', 'Lead Rigger / Scaffolder Technician', NOW(), NOW()),
('117649', 'Haris Iswandi', 'Rigger / Scaffolder', NOW(), NOW()),
('118593', 'Haris Pristanto', 'Rigger / Mechanic', NOW(), NOW()),
('6370', 'Hasanudin', 'Rigger / Scaffolder', NOW(), NOW()),
('42821', 'Heri Kristanto', 'Field Surveyor', NOW(), NOW()),
('52881', 'Hevan Desumaya', 'Mech. / Piping Supv.', NOW(), NOW()),
('96477B', 'Idris', 'Lead Rigger / Scaffolding Assessor', NOW(), NOW()),
('1081', 'Ihsanudin', 'Mech. / Piping Supv.', NOW(), NOW()),
('102008', 'Ijang Syaepudin', 'Rigger / Scaffolder', NOW(), NOW()),
('97562', 'Iwan Setiawan', 'Mech. / Piping Supv.', NOW(), NOW()),
('119018', 'Jaenal Mahardi', 'Rigger / Scaffolder', NOW(), NOW()),
('77430', 'Jamroni', 'Rigger / Scaffolder', NOW(), NOW()),
('117943', 'Jumino', 'Rigger / Scaffolder', NOW(), NOW()),
('22242', 'Juni Fahruri', 'Lead Rigger / Scaffolder Technician', NOW(), NOW()),
('117590', 'Kandeg', 'Rigger / Scaffolder', NOW(), NOW()),
('119019', 'Kardono', 'Rigger / Scaffolder', NOW(), NOW()),
('27048', 'Karna Birawa', 'Fitter / Rigger', NOW(), NOW()),
('118413', 'Khoirul Sobirin', 'Rigger / Scaffolder', NOW(), NOW()),
('118491', 'Komarudin', 'Rigger / Scaffolder', NOW(), NOW()),
('117586', 'Kristianto Handoyono', 'Lead Rigger / Scaffolder Technician', NOW(), NOW()),
('1114', 'Loren', 'Mech. / Piping Supv.', NOW(), NOW()),
('87977', 'Lucksor Situmorang', 'Rigger / Scaffolding Assessor', NOW(), NOW()),
('25967', 'M. Arifin', 'Lead Rigger / Scaffolding Assessor', NOW(), NOW()),
('118484', 'Mahmudi', 'Rigger / Scaffolder', NOW(), NOW()),
('118441', 'Makpudin', 'Mech. / Piping Supv.', NOW(), NOW()),
('79602', 'Marfin Lainsamputty', 'Rigger / Scaffolder', NOW(), NOW()),
('97455', 'Maskaryadi', 'Lead Rigger / Scaffolding Assessor', NOW(), NOW()),
('118408', 'Mastuni', 'Rigger / Scaffolder', NOW(), NOW()),
('22161', 'Mastur', 'Rigger / Scaffolder', NOW(), NOW()),
('78529', 'Mohammad Jabidi', 'Lead Rigger / Scaffolder Technician', NOW(), NOW()),
('21062', 'Muh. Saekon', 'Rigger / Scaffolder', NOW(), NOW()),
('4322', 'Muhammad Khojin', 'HTW/HWC Technician', NOW(), NOW()),
('118442', 'Muhammad Nurdin', 'Rigger / Scaffolder', NOW(), NOW()),
('30223', 'Mujiono', 'Mepi/Instrument Supv.', NOW(), NOW()),
('117656', 'Nardi', 'Rigger / Scaffolder', NOW(), NOW()),
('117675', 'Ngadirun', 'Rigger / Scaffolder', NOW(), NOW()),
('118409', 'Nico Eka Putra', 'Rigger / Scaffolder', NOW(), NOW()),
('19540', 'Odriyan Isak', 'Rigger / Scaffolder', NOW(), NOW()),
('1105', 'Peter Lumalesil', 'Mech. / Piping Supv.', NOW(), NOW()),
('6371', 'Puji Waluyo', 'Mech. / Piping Supv.', NOW(), NOW()),
('77428', 'Purwanto S. B.', 'Lead Rigger / Scaffolding Assessor', NOW(), NOW()),
('68981', 'Rahmat', 'Lead Rigger / Scaffolding Assessor', NOW(), NOW()),
('106761', 'Ramses L. Gaol', 'Fitter / Rigger', NOW(), NOW()),
('117952', 'Redi Setiono', 'Welder', NOW(), NOW()),
('26002', 'Reinhard Sinaga', 'Lead Rigger / Scaffolding Assessor', NOW(), NOW()),
('118419', 'Rido Rohman', 'Rigger / Scaffolder', NOW(), NOW()),
('40621', 'Riyano', 'Lead Rigger / Scaffolding Assessor', NOW(), NOW()),
('118507', 'Riyanto (B)', 'Rigger / Scaffolder', NOW(), NOW()),
('118596', 'Rody Tuasalamony', 'Rigger / Scaffolder / Materialman', NOW(), NOW()),
('1026', 'Rudolf Kipuw', 'Project Reps.', NOW(), NOW()),
('6590', 'Samson', 'Lead Rigger / Scaffolder Technician', NOW(), NOW()),
('52301', 'Sanaji', 'Rigger / Scaffolder', NOW(), NOW()),
('117663', 'Satori', 'Rigger / Scaffolder', NOW(), NOW()),
('40641', 'Sohadi', 'Lead Rigger / Scaffolding Assessor', NOW(), NOW()),
('26163', 'Sumarlin', 'Mech. / Piping Supv.', NOW(), NOW()),
('78501', 'Sunarya', 'Lead Rigger / Scaffolding Assessor', NOW(), NOW()),
('52481', 'Surdina', 'Lead Rigger / Scaffolding Assessor', NOW(), NOW()),
('86561', 'Surnoto', 'Rigger / Scaffolder', NOW(), NOW()),
('111126', 'Sutarno', 'Rigger / Scaffolder', NOW(), NOW()),
('NOID-SUTARNO-B', 'Sutarno (B)', 'Site Surveyor', NOW(), NOW()),
('123823', 'Sutriman', 'HTW/HWC Technician', NOW(), NOW()),
('22042', 'Suwanto', 'Mech. / Piping Supv.', NOW(), NOW()),
('118075', 'Suyanto', 'Fitter / Rigger', NOW(), NOW()),
('96391', 'Syarifudin', 'Lead Rigger / Scaffolder Technician', NOW(), NOW()),
('22162', 'Tamroni', 'Lead Rigger / Scaffolding Assessor', NOW(), NOW()),
('118438', 'Tarman', 'Rigger / Scaffolder', NOW(), NOW()),
('1138', 'Tarnadi', 'Mech. / Piping Supv.', NOW(), NOW()),
('6822', 'Teddy Wijaya', 'Rigger / Scaffolder', NOW(), NOW()),
('117546', 'Toni Sultoni', 'Rigger / Scaffolder', NOW(), NOW()),
('118590', 'Tri Gunawan', 'HSE Officer', NOW(), NOW()),
('989', 'Tri Susilo H. P.', 'Mech. / Piping Supv.', NOW(), NOW()),
('97400', 'Wastoni', 'Rigger / Scaffolder', NOW(), NOW()),
('118595', 'Yudhistira Galih Saputra', 'Rigger / Mechanic', NOW(), NOW()),
('1143', 'Yulius Alvred Boeboe', 'Lead Rigger / Scaffolding Assessor', NOW(), NOW()),
('87747', 'Zarkasih Hidayat', 'Lead Rigger / Scaffolding Assessor', NOW(), NOW()),
('121501', 'M. Rizal Fahrevi', 'Civil Technician', NOW(), NOW()),
('120809', 'Komarudin (B)', 'Civil Technician', NOW(), NOW()),
('103146', 'Ridwan', 'Civil Technician', NOW(), NOW()),
('120792', 'Ropani', 'Civil Technician', NOW(), NOW()),
('117527', 'Munir Suhendra', 'Civil Technician', NOW(), NOW()),
('117534', 'Didin (B)', 'Civil Technician', NOW(), NOW()),
('120791', 'Sandi', 'Civil Technician', NOW(), NOW()),
('117665', 'Ata', 'Civil Technician', NOW(), NOW()),
('120949', 'Muksin', 'Civil Technician', NOW(), NOW()),
('117568', 'Reja Kurniawan', 'Civil Technician', NOW(), NOW()),
('123318', 'Abdul Manap', 'Civil Technician', NOW(), NOW()),
('123319', 'Jajang', 'Civil Technician', NOW(), NOW()),
('123325', 'Ikhsan Maulana', 'Civil Technician', NOW(), NOW()),
('123320', 'Andri Suhendra', 'Civil Technician', NOW(), NOW()),
('125581', 'Nopiana', 'Civil Technician', NOW(), NOW()),
('129918', 'Agun', 'Civil Technician', NOW(), NOW()),
('125198', 'Herlan', 'Civil Technician', NOW(), NOW()),
('125196', 'Agus Asep', 'Civil Technician', NOW(), NOW()),
('118389', 'Jumali', 'Civil Technician', NOW(), NOW()),
('118383', 'Kadim', 'Civil Technician', NOW(), NOW()),
('127695', 'Wastorih', 'Civil Technician', NOW(), NOW()),
('120785', 'Mikroz', 'Civil Technician', NOW(), NOW()),
('121350', 'Subandi', 'Civil Technician', NOW(), NOW()),
('118382', 'Perdi Hasan', 'Civil Technician', NOW(), NOW()),
('127692', 'Karnila', 'Civil Technician', NOW(), NOW()),
('127696', 'Tarsadi', 'Civil Technician', NOW(), NOW()),
('127697', 'Sunoto', 'Civil Technician', NOW(), NOW()),
('127693', 'Heri Yanto', 'Civil Technician', NOW(), NOW()),
('130526', 'Achmad Affandi', 'Civil Technician', NOW(), NOW()),
('127694', 'Fajar Siddiq D.', 'Civil Technician', NOW(), NOW()),
('130511', 'Suryana', 'Civil Technician', NOW(), NOW()),
('130546', 'Amrin', 'Civil Technician', NOW(), NOW()),
('133671', 'Sunaryo', 'Civil Technician', NOW(), NOW()),
('124796', 'Arif Budiman', 'Civil Technician', NOW(), NOW()),
('3868', 'Saepudin (B)', 'Rigger / Scaffolder', NOW(), NOW()),
('118488', 'Ardin Arsad', 'Rigger / Scaffolder', NOW(), NOW()),
('94351', 'Achmad Jaelani', 'Rigger / Scaffolder', NOW(), NOW()),
('124279', 'Agus Ginanjar', 'Fitter', NOW(), NOW()),
('3078', 'Henry De Presley', 'Rigger / Scaffolder', NOW(), NOW()),
('124270', 'Fandy Susantyo', 'Rigger / Scaffolder', NOW(), NOW()),
('124369', 'Dafitra Satya', 'Rigger / Scaffolder', NOW(), NOW()),
('124266', 'Chairunnas', 'Rigger / Scaffolder', NOW(), NOW()),
('124272', 'Nopiansah', 'Rigger / Scaffolder', NOW(), NOW()),
('119066', 'Akbar Tanjung Mustofa', 'Rigger / Scaffolder', NOW(), NOW()),
('124265', 'Yayan Suparman', 'Rigger / Scaffolder', NOW(), NOW()),
('124276', 'Iim Abdul Rochim', 'Rigger Technician', NOW(), NOW()),
('124280', 'Fadly Rachman', 'Rigger / Scaffolder', NOW(), NOW()),
('124268', 'Johan', 'Rigger / Scaffolder', NOW(), NOW()),
('86077', 'Eko Siantoro', 'HTW/HWC Technician', NOW(), NOW()),
('86077B', 'Nanang Iriyanto', 'Rigger / Mechanic', NOW(), NOW()),
('124283', 'Indra Mustaqim', 'Rigger / Mechanic', NOW(), NOW()),
('124920', 'Dian Febriansyah', 'HTW/HWC Technician', NOW(), NOW()),
('124267', 'Edi Susanto (B)', 'Rigger / Scaffolder', NOW(), NOW()),
('124982', 'Hendradi Aprin Saputro', 'HSE Officer', NOW(), NOW()),
('1088', 'Roni Jemi F.', 'Lead Rigger / Scaffolding Assessor', NOW(), NOW()),
('127462', 'Bayu Putra Perdana', 'HTW/HWC Technician', NOW(), NOW()),
('127275', 'M. Ikhsan Ghassani', 'Rigger / Scaffolder', NOW(), NOW()),
('78368', 'Rudi. M Simanjuntak', 'Field Surveyor', NOW(), NOW()),
('3077', 'Dafid Ladi A.', 'Welder', NOW(), NOW()),
('129686', 'Rian Gading Perkasa', 'Welder', NOW(), NOW()),
('129681', 'Adiksa Arya Purnatama', 'Welder', NOW(), NOW()),
('93862', 'Ariya Agesta', 'Rigger / Scaffolder', NOW(), NOW()),
('123818', 'Anwar Anam', 'HTW/HWC Technician', NOW(), NOW()),
('129771', 'Solehudin', 'Rigger / Mechanic', NOW(), NOW()),
('129783', 'Rafli Abdul Fatach', 'Rigger / Mechanic', NOW(), NOW()),
('118139', 'Indra Rukmana', 'HSE Officer', NOW(), NOW()),
('31562', 'Heru Susilo', 'HTW/HWC Technician', NOW(), NOW()),
('127707', 'Galan Reza Azhari', 'HTW/HWC Technician', NOW(), NOW()),
('97127', 'Syahrudin Nasution', 'Fitter', NOW(), NOW()),
('130387', 'Abdul Faqih A.', 'Fitter', NOW(), NOW()),
('130469', 'Viery Andriyanto', 'HTW/HWC Technician', NOW(), NOW()),
('127712', 'Rangga Arya Pratama', 'HTW/HWC Technician', NOW(), NOW()),
('130148', 'Ridho Kurniawan', 'HTW/HWC Technician', NOW(), NOW()),
('130390', 'Tedy Anwar Laila', 'HTW/HWC Technician', NOW(), NOW());
